### PR TITLE
Fork #123 of feat(options): Add a `hrefFn` option to build the URL to prefetch.

### PR DESCRIPTION
**Pull request by gilbertococchi**
This is a fork of GoogleChromeLabs#123 with test fixes to be able to merge this into the main repo.

@addyosmani, @thearegee FYI

### CODE REVIEW

**Comment by gilbertococchi** [comment]
@ruben0626  to review

**Review by addyosmani — CHANGES_REQUESTED** [review]
Overall changes LGTM. One request: can we add a recipe/example of usage to the README? We currently have an API entry but showing how developers should use this new option would also be helpful.

**Comment by gilbertococchi** [comment]
@addyosmani sure you are right, I've added a simple example within the demos folder here https://github.com/GoogleChromeLabs/quicklink/pull/201/commits/769653c0e1d56c84d4db04c0464465769e0e9ee5.

**Review by addyosmani — CHANGES_REQUESTED** [review]
LGTM with some minor changes.

**Review by addyosmani — APPROVED** [review]
LGTM

**Pull request merged**
