### PR TITLE
Bugfix/syntax highlighting site

### PR DESCRIPTION
**Pull request by anton-karlovskiy**
1. highlight.js is up-to-date (v9.16.2) so some broken syntax highlighting is fixed by upgrading the lib
2. syntax highlighting is restored
3. linked CDN css for syntax highlighting and removed local css file

### CODE REVIEW

**Comment by addyosmani** [comment]
Thanks!

**Comment by addyosmani** [comment]
Hmm. I need to dig into this further when not on mobile, but it looks like our latest deploys are having challenges with syntax highlighting again (this fix was included).

I'll debug later in the day, but just wanted to highlight this.

https://quicklink-6a87b.firebaseapp.com/

**Comment by anton-karlovskiy** [comment]
@addyosmani 

Let me debug it too.

**Comment by anton-karlovskiy** [comment]
@addyosmani 

quicklink-syntax-highlighting-mobile
quicklink-syntax-highlighting

On my side, I think syntax-highlighting looks okay.
Could you please let me know what is broken?

**Comment by addyosmani** [comment]
Hey Anton. After retesting syntax highlighting on the current deployment it does appear to be working. I'll chalk up my previous tests to there being a caching issue of some sort :)

**Pull request merged**
