### PR TITLE
Adding React SPA demos to repo and site

### PR DESCRIPTION
**Pull request by demianrenzulli**
cc // @addyosmani @anton-karlovskiy

### CODE REVIEW

**Comment by demianrenzulli** [comment]
Good question, Addy. I've noticed that also (unlike the links the other demos).

I created that link by going to Tools->Import and Export->Git URL. The tool doesn't let me edit the URL. I'm wondering if you did something different for the other demos, or perhaps Glitch has changed the way it generates the URLs lately?

Alternatively we can use the URL of my repo: 

git clone git@github.com:demianrenzulli/create-react-app-unejected-quicklink.git

Any ideas are welcome!

**Comment by anton-karlovskiy** [comment]
@demianrenzulli cc @addyosmani 

Could you please try `git clone https://api.glitch.com/git/create-react-app-quicklink`?
I tried myself and it's working. I'm afraid I'm not sure of the reason.

**Comment by demianrenzulli** [comment]
Thanks @anton-karlovskiy! Removing the hash that Glitch generates seems to just work 👍

Changed it to the new URL.

**Comment by addyosmani** [comment]
Thank you for these additions folks!

**Pull request merged**
