### PR TITLE
[infra] Add site updates for 2.0.0

### PR DESCRIPTION
**Pull request by addyosmani**
In-flight site updates for 2.0.0.

### CODE REVIEW

**Comment by demianrenzulli** [comment]
@addyosmani now we have approval from the company, changes LGTM 👍

**Comment by addyosmani** [comment]
@demianrenzulli fantastic. Yay.

Any other site-related changes (other than bumping the version number + tag) that we're wanting to land for this release? (e.g is the React demos related work you and Anton are driving planned for the README or README + site?)

**Comment by demianrenzulli** [comment]
Good catch! I'd like to edit the demo section of the site to clearly separate between MPAs and SPAs and the latest ones.

Do you think the current ones deployed in Glitch can be used for that? Or do you think we'll end up uploading it somewhere else? If not, I can work on these changes for the site as well.

**Comment by demianrenzulli** [comment]
Perhaps it's a better to just move forward with this PR, and then I can take care of updating the site once we have decided where to host these demos? That way I don't block these changes.

**Comment by addyosmani** [comment]
SG.

**Pull request merged**
