### PR TITLE
Feature/demo news

### PR DESCRIPTION
**Pull request by anton-karlovskiy**
- created news, news-workbox demo projects
- fixed menu links at the top
- integrated quicklink into news demo, quicklink and service worker with workbox into news-workbox demo
- updated dependencies to date
- locally built and tested
- tested on glitch
- added readmes

### CODE REVIEW

**Comment by anton-karlovskiy** [comment]
> signed it

**Comment by anton-karlovskiy** [comment]
Travis is trying to install yarn 1.3.2 and the current stable release is 1.16.0

Passing config:
$ node --version
v11.11.0
$ npm --version
6.7.0
$ nvm --version
0.34.0
$ yarn --version
1.3.2

Failing config:
$ node --version
v12.4.0
$ npm --version
6.9.0
$ nvm --version
0.34.0
$ yarn --version
1.3.2

**Comment by addyosmani** [comment]
I've fixed the build issues on the main repo now. What I wanted for the PR here was for us to just include the README with a link to the Glitch, but not commit the source (leaving source in the Glitch). That allows us to avoid committing all the demos to the repo (which would increase git pull times).

Could we remove the source for individual demos from the PR and just include READMEs with links to the Glitches? :)

**Comment by anton-karlovskiy** [comment]
> I've fixed the build issues on the main repo now. What I wanted for the PR here was for us to just include the README with a link to the Glitch, but not commit the source (leaving source in the Glitch). That allows us to avoid committing all the demos to the repo (which would increase git pull times).
> 
> Could we remove the source for individual demos from the PR and just include READMEs with links to the Glitches? :)

Yes for sure. I'll remove the sources and just include READMEs with links.

**Comment by anton-karlovskiy** [comment]
Can you please have a look at README?
I'd like you to give me some tips on how to write it according to convention or something.

**Comment by addyosmani** [comment]
Certainly. My feedback on the READMEs:

- Can we change the titles from "Lab" to "Demo"?
- Can we provide a slightly longer description for each demo. Example: A demo showing how to use Quicklink on a simple multi-page website. Example: A demo showing how to use Quicklink with Workbox for offline caching and links in the visible viewport.
- Can we update the names/subdomain names on the Glitch URLs to something simpler? e.g "quicklink-basic-demo", "quicklink-workbox-demo"?
- Can we drop the not a Google product section?
- It might be useful for us to also include some guidance on how to git clone / npm install / npm build the demos, in case someone wants to get a local version of the Glitch. Glitch supports GIT URLs for cloning that we could leverage here.

I think that's it. Is that helpful feedback?

**Comment by anton-karlovskiy** [comment]
I've investigated for custom domain in glitch.
They say it's possible.
https://glitch.com/help/custom-domain/
But on my side the custom domain button is disabled.
Looks like it's issue with glitch itself.

**Pull request merged**
