### PR TITLE
feat(index.mjs): normalize URLs being prefetched (fixes #27)

### PR DESCRIPTION
**Pull request by addyosmani**
reviewers proposed: @lukeed @mathiasbynens

### CODE REVIEW

**Comment by addyosmani** [comment]
Luke also proposed the `prefetch(new URL(url), priority)` abbreviation.

**Comment by addyosmani** [comment]
One fyi downside to this change is that while previously "loose" paths would prefetch without issue (['2.html', '4.html']), at least based on our tests, fully qualified paths are now required (`['http://127.0.0.1:8080/test/2.html','http://127.0.0.1:8080/test/4.html']`).

**Comment by lukeed** [comment]
We could do `new URL(url, location.href)`, which builds a URL string w/ 2nd arg as reference

**Comment by addyosmani** [comment]
> We could do new URL(url, location.href), which builds a URL string w/ 2nd arg as reference

Great idea. This allowed reverting back to the old tests and appears to have done the trick. I'll hold off on landing this to give @mathiasbynens a chance to sanity check what we're doing here.

**Comment by mathiasbynens** [comment]
LGTM!

**Comment by addyosmani** [comment]
Thanks folks!

**Pull request merged**
