### PR TITLE
fix:Uncaught (in promise)

### PR DESCRIPTION
**Pull request by ChuanfengZhang**
May not be a good solution, but works:)
https://github.com/GoogleChromeLabs/quicklink/issues/59#issuecomment-448353766
ref: #59 
cc: @lukeed

### CODE REVIEW

**Comment by addyosmani** [comment]
@lukeed do you know if this one is still needed for the uncaught error?

**Comment by lukeed** [comment]
This will catch them, but it'll be silent to the console _and_ to the developer.

Maybe the ideal is to make quicklink accept an error handler, which gets passed into our [`prefetcher` wrapper](https://github.com/GoogleChromeLabs/quicklink/blob/master/src/index.mjs#L39-L42), else noop.

That way, the `prefetch` itself has no built-in silencing an those who load it directly don't fight against it.

Something like this?

```js

const noop = () => {};

// main
export default function (options) {
  if (!options) options = {};
  
  // Attach ref to `toPrefetch` set
  toPrefetch.fetch = url => {
    toPrefetch.delete(url);
    prefetch(new URL(url, location.href).toString(), observer.priority).catch(options.onError || noop);
  };
  
  // ...
}

const observer = new IntersectionObserver(entries => {
  entries.forEach(entry => {
    if (entry.isIntersecting) {
      const link = entry.target;
      if (toPrefetch.has(link.href)) {
        observer.unobserve(link);
        // -- prefetcher(link.href);
        toPrefetch.fetch(link.href);
      }
    }
  });
});
```

**Comment by addyosmani** [comment]
Hey folks. There hasn't been much further movement on this issue since April. With this in mind, @ChuanfengZhang did you have thoughts on adjusting your proposed solution per the snippet @lukeed was kind enough to share? 

Thumbs up on the original issue in #59 appear to suggest a few users have run into this. Would love to gauge interest in someone completing this patch (or us closing this PR if we don't think we'll be heading down this path further).

**Comment by addyosmani** [comment]
Closing this PR for now. Please feel free to open up a new issue if there's interest in picking this back up :)

**Pull request closed without merging**
